### ISSUE TITLE
Exported GLTF mesh's filenames missing a dot before extension

### ISSUE THREAD

**Issue by lincerely** [dlannan/defold-blender-export#10]
As the title says, the GLB export works but not the GLTF.

This is caused by the following line,

https://github.com/dlannan/defold-blender-export/blob/ae50f61b21dd558fb60a397bd6f5c413a6a90f92/blender/addons/defender/defoldsync/generator.lua#L657

...which it assumed the extension with dot is 4 letters, but ".gltf" is 5. 

Adding the following line below it would fix this issue.

```lua
if( gltf_ext == "gltf") then gltf_ext = ".gltf" end
```

**Comment by dlannan** [comment]
Ahh thanks. I'll add that fix in asap. Appreciate the feedback.

**Comment by dlannan** [comment]
Latest release has a fix (more correctly detect extensions) and a fix for gltfs using bin files.
https://github.com/dlannan/defold-blender-export/releases/tag/v1.3.2
