### ISSUE TITLE
The addon just don't work

### ISSUE THREAD

**Issue by Caue-Aron** [dlannan/defold-blender-export#7]
I properly set up everything, gave admin permission to both blender and the interpreter, but still, when I click to sync it doesnt do anything. Thats my scene:
![image](https://user-images.githubusercontent.com/54822334/187330938-ba4e6a20-c490-41d8-b46c-afbd72472fe4.png)

**Comment by dlannan** [comment]
Hi Caue-Aron. 
Quick checklist: 
- Did you enable permissions on the luajit executable file (this is specifically needed). Blender can still be user permissions. 
- Check you are in "Object Mode" (the panel wont show without it anyway)
- Make sure the materials are Principled BSDF. These are the only supported materials at this time (soon to support much more).
- Check the materials are one material per object. 
- Make sure you select the collection you want to export. 

I suspect its the last issue. Some scenes you can have many collections, and so it uses the one which is currently selected - you can select an object within it, and that should also select the collection. 

I might also check on the object iteration. It might be doing something odd

I might make it an option to set the collection in the panel - making it a little more clear. 

To be clear, Collections in Blender become Collections in Defold.
Let me know if this helps.

**Comment by dlannan** [comment]
Can you also post a picture of the panel, so I can check the settings you are using. 
Also, you can open the info panel, and if there are any errors, they should appear there.

Oh. also. Can you provide some details about Blender version, OS you are working on, and path arrangement - check the path you are exporting to has write permissions (ie not protected).

**Comment by dlannan** [comment]
Looking again. I can see that there is no collection in this scene. All objects need to live in a collection.
The root "Scene Collection" is a world container. The goal of Defender is to map Collections in Blender to Collections in Defold. 
I'll add some error handling and logging for this, as well some more documentation on the requirements for your scene.
