### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SamsTheGreatest** [dlannan/defold-blender-export#9]
OS: MacOS Ventura

Hi, I am trying to export a demo monkey but get error on line 346 in init `subprocess.check_output([luajit_cmd, dirpath, os.path.abspath(dir)])`.

**Comment by dlannan** [comment]
Hi, can you check a couple of things first.
- did you make sure the luajit binary that was installed in the blender/addons/defender/defoldsync/luajit/darwin/ is able to be executed by your logged in user. 
- also check on the macOS that you can run that luajit from the command line: try something like luajit -v. You should see a response like "LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/"

Hopefully it will be related to these (Check the documentation in the main page or the defold forum - we have covered many issues there).
https://forum.defold.com/t/building-a-sync-tool-for-blender-to-defold/69920/43

**Comment by dlannan** [comment]
No response. marking as resolved.
